# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'signup-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['signup-service:5002']

  - job_name: 'login-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['login-service:5003']

  - job_name: 'orchestration-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['orchestration-service:5005']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
